### ISSUE TITLE
Publish on jsr

### ISSUE THREAD

**Issue by rrd108** [rrd108/vue-mess-detector#7]

**Comment by rrd108** [comment]
https://jsr.io/@rrd/vue-mess-detector

**Comment by rrd108** [comment]
@brenoepics can you look into this. I have tried quite a few variations but it always fails

**Comment by rrd108** [comment]
the jsr publish fails. I modified a lot but still fails with different errors.

For example: https://github.com/rrd108/vue-mess-detector/actions/runs/11221618034/job/31192321609

**Comment by brenoepics** [comment]
I fixed the action in a fork and managed to publish it, I've never used jsr, I don't know if I'm doing it wrong, but I believe that pnpm, npm... doesn't recognize `@username/package` as a command and tries to download it from npm central.

example

1. publish to jsr
2. `npx jsr add @brenoepics/testing`
3. `npx @brenoepics/testing analyze`

Upon observing this, I thought about searching for jsr commands to see if there were any similar to a dlx, unfortunately, there aren't, I found an issue related to this.
https://github.com/jsr-io/jsr/issues/157

**Comment by rrd108** [comment]
https://jsr.io/docs/publishing-packages#publishing-from-github-actions

Here is the detailed info how to do this

**Comment by brenoepics** [comment]
publishing is easy, actually it was just missing the node setup step, but running bin commands seems not possible.
working example:

```yaml
name: JSR Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - run: |
          yarn install
          npx jsr publish --allow-dirty
```
